language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build --platform=linux/amd64 -t reverseproxy:v1 ./udagram-reverseproxy

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - docker tag udagram-api-feed kienhoangg/udagram-api-feed
  - docker tag udagram-api-user kienhoangg/udagram-api-user
  - docker tag udagram-frontend kienhoangg/udagram-frontend
  - docker tag reverseproxy:v1 kienhoangg/udagram-reverseproxy:v1

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push kienhoangg/udagram-api-feed
  - docker push kienhoangg/udagram-api-user
  - docker push kienhoangg/udagram-frontend
  - docker push kienhoangg/udagram-reverseproxy:v1
