apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  selector:
    service: backend-user
  ports:
    - port: 8080
      targetPort: 8080
      name: '8080'
