apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  selector:
    service: backend-feed
  ports:
    - port: 8080
      targetPort: 8080
      name: '8080'
